"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

#& for jwt
from datetime import timedelta

#& module python standard permettant d'acceder aux variables locales
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# cast string to bool : os.environ.get() always returns a string,
# so we compare it to 'True' to get a real Python boolean
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# split string to list : os.environ.get() always returns a string
# we split it by ',' to get a real Python list
# 'localhost' is the fallback value if ALLOWED_HOST is not defined in the .env file
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOST', 'localhost').split(',')

#? ----------------------------------------------------------------------------
#? Application definition
#? ----------------------------------------------------------------------------

JAZZMIN_SETTINGS = {
    "site_title": "Transcendence Admin",
    "site_header": "Transcendence",
    "site_brand": "Transcendence",
    "welcome_sign": "Welcome to Transcendence",
    "theme": "darkly",  # ← thème bleu/sombre sympa
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "default_theme_mode": "auto",
    "button_classes": {
        "primary": "btn-primary",
    }
}

INSTALLED_APPS = [

    #'daphne', # New import chat
    
    # django apps
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # other apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    'apps.chat.apps.ChatConfig', # New import chat

    # personnal apps
    "apps.users",
    "apps.api",
    #"apps.chat",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

#? ----------------------------------------------------------------------------
#? Database
#? ----------------------------------------------------------------------------

#& ENGINE : replace sqlite3 with psotgres (connexion by psycop2 -> requirements docker)
#& os : permet de lire les variables d'environnement locales dans .env
#& NAME     : nom de la base de donnees
#& USER     : utilisateur (admin ?)
#& PASSWORD : mot de passe
#& HOST     : nom du conteneur postgresgl dans docker compose
#& PORT     : port standard postgresql

# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': 'db',
        'PORT' : '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

#? ----------------------------------------------------------------------------
#? CustomUser model
#? ----------------------------------------------------------------------------
#&  -  must be set before first migration
#& Must be defined before running any migrations

AUTH_USER_MODEL = 'users.User'

#? ----------------------------------------------------------------------------
#? Media files (user uploads like avatars)
#? ----------------------------------------------------------------------------
#& MEDIA_URL : the public URL to access media files (media/avatars/photo.jpg)
#& MEDIA_ROOT : the absolute path on disk where files are stored

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


#? ----------------------------------------------------------------------------
#? Static files (CSS, JavaScript, Images)
#? ----------------------------------------------------------------------------
#& https://docs.djangoproject.com/en/6.0/howto/static-files/
#& STATIC_URL : the public URL to access static files
#& STATIC_ROOT : the folder where 'collectstatic' gathers all static files

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

#? ----------------------------------------------------------------------------
#? CORS configuration
#? ----------------------------------------------------------------------------
#& Allows Angular (localhost:4200) to communicate with Django API (localhost:8000)
#& Without this , the browser blocks all cross-origin requests.
#& CORSL_ALLOW_CREDENTIALS  : allows cookies and auth headers to be sent cross-origin

#TODO ajouter a la liste autorise http://transcendence.com en prod

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200", #& Angular
    "http://localhost:5500", #& page de test
    "http://127.0.0.1:5500", #& file://
    "http://127.0.0.1:5501", #& live server
]

CORS_ALLOW_CREDENTIALS = True

#? ----------------------------------------------------------------------------
#? DRF (Django REST Framework) configuration
#? ----------------------------------------------------------------------------
#& DRF is a toolkit that transforms Django views into a REST API
#& JWT (JSON Web Token) is used for authentication instead of session
#& Angular sends the token in every request header to prove its identity

REST_FRAMEWORK = {

    #& use JWT authentication instead of Django's default session authentication
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    #& by default, only authenticated users can access the API
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.IsAuthenticated',
    ],
}

#? ----------------------------------------------------------------------------
#? JWT (JSON Web Token) configuration
#? ----------------------------------------------------------------------------
#& ACCESS_TOKEN  : short-lived token sent with every API request (5 min)
#& REFRESH_TOKEN : long-lived token used to get a new access token (1 day)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),  #& token expires is 5 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1) ,    #& token expires in 1 day
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

'''
#& TECHNICAL REQUIREMENT: LOGIN WITH EMAIL
    #& Specifies which field in the User model is used to identify the user inside the token payload.
    #& Keeping 'id' (database primary key) ensures str(token["user_id"]) matches request.user.id in LogoutView.
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
'''

#? ----------------------------------------------------------------------------
#? Django Channels configuration
#? ----------------------------------------------------------------------------
#& Channels extends Django to handle WebSockets and long-running connexions
#& WebSockets are required for the live chat feature
#& ASGI application replaces the default WSGI application

ASGI_APPLICATION = 'core.asgi.application'

#? ----------------------------------------------------------------------------
#? Channel Layers configuration
#? ----------------------------------------------------------------------------
#& Redis is used as a message broker between WebSocket connections
#& When a user A sends a message, Redis broadcasts it to all connected users
#& Host 'redis' refers to the Redis container name in docker compose

# new migration chat
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             'hosts':[('redis', 6379)],
#         },
#     },
# }



CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}
