# Generated by Django 6.0.5 on 2026-05-23 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_friendship'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='friends',
                    field=models.ManyToManyField(blank=True, through='friends.Friendship', to=settings.AUTH_USER_MODEL),
                ),
            ],
            database_operations=[],
        ),
    ]
