# Generated by Django 6.0.5 on 2026-05-24 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_remove_friendship_unique_friendship_pair_and_more'),
        ('users', '0002_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, through='friends.Friendship', through_fields=('user_id', 'friend_user_id'), to=settings.AUTH_USER_MODEL),
        ),
    ]
