# Generated by Django 6.0.5 on 2026-05-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
        ('users', '0003_alter_user_friends'),
    ]

    operations = [
    ]
