# Generated by Django 6.0.6 on 2026-06-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_is_2fa_enabled'),
        ('users', '0005_socialaccount'),
    ]

    operations = [
    ]
