# Generated by Django 6.0.6 on 2026-06-19 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_add_is_2fa_enabled'),
        ('users', '0005_socialaccount'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE users_user ALTER COLUMN is_2fa_enabled SET DEFAULT false; UPDATE users_user SET is_2fa_enabled = false WHERE is_2fa_enabled IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='is_2fa_enabled',
                    field=models.BooleanField(default=False, verbose_name='2FA enabled'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('42', 'École 42')], max_length=20, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, through='friends.Friendship', through_fields=('user_id', 'friend_user_id'), to=settings.AUTH_USER_MODEL, verbose_name='Friends'),
        ),
    ]
