# Generated by Django 6.0.6 on 2026-06-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_socialaccount_created_at_and_more'),
        ('users', '0006_merge_0005_add_is_2fa_enabled_0005_socialaccount'),
    ]

    operations = [
    ]
