# Generated by Django 6.0.6 on 2026-06-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_is_2fa_enabled'),
        ('users', '0007_merge_20260620_0802'),
    ]

    operations = [
    ]
