
#? -----------------------------------------------------------------------------
#? Default Django models
#? -----------------------------------------------------------------------------

# Import Django's built-in user model to extend it
from django.contrib.auth.models import AbstractUser

# Import Django's model module to define database fields
from django.db import models

#? -----------------------------------------------------------------------------
#? CUSTOM USER MODEL - EXTENDING DJANGO'S ABSTRACTUSER
#? -----------------------------------------------------------------------------
# By inheriting from AbstractUser, our custom User model automatically gets
# all of Django's built-in authentication features:
#   - Authentication : Login, logout, password hashing.
#   - Permissions    : is_staff, is_superuser, groups, user_permissions.
#   - Default fields : username, email, date_joined, last_login.
#
# WHY DEFINE A CUSTOM MODEL?
# --------------------------
# It is a "Best Practice" to define a custom User model at the start of any 
# project. This allows us to add custom fields without resetting the 
# database later.
#
# CUSTOM FIELDS ADDED:
# --------------------
#   - avatar      : Profile picture stored in 'media/avatars/'.
#   - is_online   : Tracks connection status (useful for real-time chat).
#   - otp_secret  : Secret key for Two-Factor Authentication (2FA).
#   - friends     : Many-to-Many relationship with itself. Django 
#                   automatically creates an intermediate table: 
#                   'users_user_friends' (from_user_id | to_user_id).
#   - role        : Role-based access control (User or Admin).
#
# @property avatar_url:
# ---------------------
#   This decorator transforms a method into an attribute (accessible as 
#   'user.avatar_url').
#   - If an avatar is uploaded: Returns the file URL (e.g., /media/avatars/x.jpg).
#   - If no avatar exists: Returns a unique robot generated by DiceBear API.
#   - The seed (username) ensures a consistent avatar across all sessions.
#
# RELATED_NAME CONFLICTS:
# -----------------------
#   We redefine 'groups' and 'user_permissions' to avoid naming conflicts 
#   with Django's default User model during migrations.
# -----------------------------------------------------------------------------

class User(AbstractUser):
	
	# List of roles
	class Role(models.TextChoices):
		USER = 'user', 'User'
		ADMIN = 'admin', 'Admin'

	# Name displayed in the Django admin panel for User model
	class Meta:
		verbose_name = 'User'
		verbose_name_plural = 'Users'
	
	# Profile picture uploaded by the user
	# null=True, blank=True make this field optional
	avatar = models.ImageField(
		upload_to='avatars/',
		null=True,
		blank=True,
		verbose_name='Profile picture'
	)

	# Tracks whether the user is currently connected
	is_online = models.BooleanField(
		default=False,
		verbose_name='Online status'
	)

	# Stores the secret key used for Two-Factor Authentication (2FA)
	otp_secret = models.CharField(
		max_length=32,
		blank=True,
		verbose_name='2FA secret key'
	)

	# Many-to-many relationship with itself to store the user's friends list
	# Symetrical=True is the default for 'self' relationships 
	friends = models.ManyToManyField(
		'self',
		blank=True
		
	)
	
	# Role-based access control - defaults to USER for every new account
	# Can only used by the superuser via the Django admin panel
	role = models.CharField(
		max_length=20,
		choices=Role.choices,
		default=Role.USER,
		verbose_name='User role'
	)

	# Redefined to avoid related_name conflicts with Django's default User model
	# related_name='customuser_set' -> convention Django
	# related_name='+' -> disable inverse relation
	
	groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to.',
        related_name='customuser_set',
        related_query_name='user',
    )

	user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='customuser_set',
        related_query_name='user',
    )

	# Return e-mail if available, otherwise return username
	def __str__(self):
		if self.email:
			return self.email
		return self.username
	
	@property
	def avatar_url(self):
		"""
        Returns the appropriate avatar URL:
        1. If a file is uploaded, return its URL.
        2. Otherwise, return a robot avatar from DiceBear using username as seed.
        """
		if self.avatar:
			return self.avatar.url
		return f'https://api.dicebear.com/9.x/bottts/svg?seed={self.username}'
    
    

#* 
#?
#&
#!
#%
#TODO
#DEBUG
