"""
# =============================================================================
# MODELS - apps/users/models.py
#
# The Model defines the database structure (The "Source of Truth").
# We extend Django's AbstractUser to keep all built-in security features
# while adding our custom social and status fields.
# =============================================================================
"""



#* =============================================================================
#* IMPORT
#* =============================================================================

# 1. Django's core user base to inherit authentication & permissions logic
from django.contrib.auth.models import AbstractUser

# 2. Django's field definitions for database columns
from django.db import models

#? -----------------------------------------------------------------------------
#? CUSTOM USER MODEL - THE ARCHITECTURE
#? -----------------------------------------------------------------------------
#?
#?   WHY DEFINE A CUSTOM MODEL?
#?   --------------------------
#?   It is a "Best Practice" to define a custom User model at the start of any 
#?   project. This allows us to add fields (like avatar or online status) 
#?   without breaking the database later.
#?
#?   WHAT DO WE GET FROM ABSTRACTUSER?
#?   ---------------------------------
#?	 By inheriting from AbstractUser, our custom User model automatically gets
#?   all of Django's built-in authentication features:
#?   - Authentication : login/logout logic and password hashing.
#?   - Permissions    : staff access, superuser status, and groups.
#?   - Default fields : username, email, date_joined, last_login.
#?
#?   CUSTOM FIELDS ADDED:
#?   --------------------
#?   - avatar      : Profile picture stored in 'media/avatars/'.
#?   - is_online   : Tracks connection status (useful for real-time chat).
#?   - otp_secret  : Secret key for Two-Factor Authentication (2FA).
#?   - friends     : Many-to-Many relationship with itself. Django 
#?                   automatically creates an intermediate table: 
#?                   'users_user_friends' (from_user_id | to_user_id).
#?   - role        : Role-based access control (User or Admin).
#?
#?   @property avatar_url:
#?   ---------------------
#?   This decorator transforms a method into an attribute (accessible as 
#?   'user.avatar_url').
#?   - If an avatar is uploaded: Returns the file URL (e.g., /media/avatars/x.jpg).
#?   - If no avatar exists: Returns a unique robot generated by DiceBear API.
#?   - The seed (username) ensures a consistent avatar across all sessions.
#?
#?   WHY REDEFINE GROUPS & PERMISSIONS?
#?   ----------------------------------
#?   When using a custom User, we must tell Django to use unique 'related_name'
#?   (customuser_set) to avoid conflicts with its internal default User model.
#? -----------------------------------------------------------------------------

class User(AbstractUser):
	
	# STEP 1 : Choices & Configuration

	# List of available roles (Semantic choices for the DB)
	class Role(models.TextChoices):
		USER = 'user', 'User'
		ADMIN = 'admin', 'Admin'

	# Meta configuration for Django Admin display
	class Meta:
		verbose_name = 'User'
		verbose_name_plural = 'Users'
	
	
	# TECHNICAL REQUIREMENT: LOGIN WITH EMAIL
    # Redefine email field to enforce uniqueness directly in the database (PostgreSQL)
	email = models.EmailField(
			unique=True, 
			verbose_name='Email address'
	)

	# Instruct Django to use the email field as the primary identifier for authentication
	USERNAME_FIELD = 'email'
	
	# The username remains mandatory, specifically for creating superusers via CLI
	REQUIRED_FIELDS = ['username']
	
	# STEP 2 : Custom Database Fields (The Columns)

	# Profile picture uploaded by the user
	# null=True, blank=True make the profile picture optional
	avatar = models.ImageField(
		upload_to='avatars/',
		null=True,
		blank=True,
		verbose_name='Profile picture'
	)

	# Tracks real-time connection status (Updated via WebSockets)
	is_online = models.BooleanField(
		default=False,
		verbose_name='Online status'
	)

	# Secret key used for 2FA (Two-Factor Authentication)
	otp_secret = models.CharField(
		max_length=32,
		blank=True,
		verbose_name='2FA secret key'
	)

	# Many-to-many relationship with itself for the friends list.
    # symmetrical=True means if I add you, we are both friends.
	friends = models.ManyToManyField(
		'self',
		blank=True,
		symmetrical=True
	)
	
	# Role-based access control - defaults to USER for every new account
	# Can only used by the superuser via the Django admin panel
	role = models.CharField(
		max_length=20,
		choices=Role.choices,
		default=Role.USER,
		verbose_name='User role'
	)

	# STEP 3 : Redefined relationships (Avoid conflicts)
	
	groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to.',
        related_name='customuser_set',
        related_query_name='user',
    )

	user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='customuser_set',
        related_query_name='user',
    )

	# STEP 4 : Methods & Properties (The Logic)

	# Return e-mail if available, otherwise return username
	def __str__(self):
		if self.email:
			return self.email
		return self.username
	
	@property
	def avatar_url(self):
		"""
        Returns the appropriate avatar URL:
        1. If a file is uploaded, return its URL.
        2. Otherwise, return a robot avatar from DiceBear using username as seed.
        """
		if self.avatar:
			return self.avatar.url
		return f'https://api.dicebear.com/9.x/bottts/svg?seed={self.username}'
    
    

#* 
#?
#&
#!
#%
#TODO
#DEBUG
