
#? -----------------------------------------------------------------------------
#? Default Django models
#? -----------------------------------------------------------------------------

# Import Django's built-in user model to extend it
from django.contrib.auth.models import AbstractUser

# Import Django's model module to define database fields
from django.db import models

#? -----------------------------------------------------------------------------
#? Custom User model
#? -----------------------------------------------------------------------------

#& -----------------------------------------------------------------------------
#& Extending Djando's default user model.
#& Always define a custom User model at the start of a project
#& to allow future modification withut database reset.
#&   - avatar		: profile picture stored in media/avatars/
#&   - is_online		: track is the user is currently connected (useful for chat)
#&   - otp_secret	: secret key for Two-Factor Authentication (2FA)
#&	 - friends		: ManyToMany realtionship with itself to store the user's
#&					  friend list> Django automatically creates an intermadiate
#&					  table in the database
#&					  Table : users_user_friends
#&					  Columns : from_user_id | to_user_id
#&	 - role			: role-based access control (user: default access, admin: full access)
#&
#& @property : decorator tranforms a method in an attribute
#& 			  -> access like a regular field 'self.avatar.url'
#&
#& self.avatar is the ImageField defined above. When an image is uploaded, Django
#& automatically provides a .url attributethat returns the full public url to access
#& to the file (/media.avatars/photo.jpg)
#& - self.avatar -> returns the fiel object (not usefull for Angular)
#& - self.avatar.url -> returns the url string (necessary for Angular to display the image)
#&
#&
#& if no avatar has been uploaded, we return a unique robot avatar generated by
#& DiceBear API based on the username as a seed. The seed ensures the same username
#& always gets the same robot avatar, so the default avatar is consistent across
#& the sessions.
#&
#& Returns the username as the string representation of the User object.
#& This is displayed in the Django admin panel and in the Dajngo shell
#& instead of the default 'User object(1)' 
#& -----------------------------------------------------------------------------

class User(AbstractUser):
	
	class Role(models.TextChoices):
		USER = 'user', 'User'
		ADMIN = 'admin', 'Admin'

	avatar = models.ImageField(upload_to='avatars', null=True, blank=True)
	is_online = models.BooleanField(default=False)
	otp_secret = models.CharField(max_length=32, blank=True)
	friends = models.ManyToManyField('self', blank=True)
	role = models.CharField(
		max_length=20,
		choices=Role.choices,
		default=Role.USER
	)

	def __str__(self):
		return self.username
	
	@property
	def avatar_url(self):
		if self.avatar:
			return self.avatar.url
		return f'https://api.dicebear.com/9.x/bottts/svg?seed={self.username}'
    
    

#* 
#?
#&
#!
#%
#TODO
#DEBUG
