'''
# =============================================================================
# SERIALIZERS - apps/users/serializers.py
#
# Serializers act as translators between JSON and Python objects.
#
# JSON → Python (deserialization) : when Angular sends data to Django
#   - Validates incoming data (required fields, email unique, password strength)
#   - Transforms JSON into a Python object ready to save in the database
                                                                                                                                                                                                        #
# Python → JSON (serialization) : when Django sends data to Angular
#   - Transforms a Python/Django object into JSON
#   - Controls which fields are returned (e.g. never return the password)
#
# Flow : Angular → URL → View → Serializer → Model → Database
# =============================================================================
'''

#* =============================================================================
#* IMPORT
#* =============================================================================

# Import Django's built-in pwd validation rules -> method validate_password
# (minimum length, no too common, not too similar to username...)
from django.contrib.auth.password_validation import validate_password

# Import DRF serializers - the translators between JSON and Python
from rest_framework import serializers

# Import custom User model to create and query users
from .models import User


#* ----------------------------------------------------------------------------
#* RegisterSerializer
#* ----------------------------------------------------------------------------
# RegisterSerializer
# Handles user registration - validates input and creates a new user.
# password is write_only : it is received but never returned in the response.
# avatar_url is read_only : it is generated and returned but never received.
class RegisterSerializer(serializers.Serializer):

    # Write-only : password is never returned in the response
    password = serializers.CharField(
        write_only=True,
        required=True,
        validators=[validate_password]
    )

    # Read-only : returned after registration (DiceBear robot URL by default)
    avatar_url = serializers.SerializerMethodField()

    # Tells the serializer which Django model to base itself on
    # ModelSerializer will automatically generate fields from this model
    # Define fields to expose in this serializer
    # - 'username'   : required input from Angular
    # - 'email'      : required input from Angular
    # - 'password'   : required input, write_only (never returned in response)
    # - 'avatar-url' : read_only, generated by the @property in the User model
    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'avatar_url')

    # def validate_field(self, value):

    def get_avatar_url(self, obj):
        # Uses the @property defined in the USer model
        return obj.avatar_url
    
    def validate_email(self, value):
        # Ensu2re email is unique acriss all users
        if User.objects.filter(email=value).exists():
            raise serializers.ValidationError("Email already exists.")
        return value
    
    def create(self, validated_data):
        # create_user automatically hashes the pwd - never store plain text
        user = User.objects.create_user(
            username=validated_data['username'],
            email=validated_data['email'],
            password=validated_data['password'],
        )
        return user

#* ----------------------------------------------------------------------------
#* UserSerializer
#* ----------------------------------------------------------------------------