'''
# =============================================================================
# SERIALIZERS - apps/users/serializers.py
#
# Serializers act as translators between JSON and Python objects.
#
# class NameSerializer(serializers.ModelSerializer)
# → creates a serializer from a django model
#
# JSON → Python (deserialization) : when Angular sends data to Django
#   - Validates incoming data (required fields, email unique, password strength)
#   - Transforms JSON into a Python object ready to save in the database
                                                                                                                                                                                                        #
# Python → JSON (serialization) : when Django sends data to Angular
#   - Transforms a Python/Django object into JSON
#   - Controls which fields are returned (e.g. never return the password)
#
# Validation levels :
#  - Level 1 - Automatic by DRF/ModelSerializer :
#     - Required fields present ?
#     - Correct types ? (email format, string length...)
#     - Constraints from the model (max_length, unique...)
#  - Level 2 - Custom validators added manually :
#     - validate_<fieldname>() : custom business rules (email unique in DB)
#     - validators=[...] : Django built-in validators (password strength)
#
# Flow : Angular → URL → View → Serializer → Model → Database
# =============================================================================
'''

#* =============================================================================
#* IMPORT
#* =============================================================================

# Import Django's built-in pwd validation rules -> method validate_password
# (minimum length, no too common, not too similar to username...)
from django.contrib.auth.password_validation import validate_password

# Import DRF serializers - the translators between JSON and Python
from rest_framework import serializers

# Import custom User model to create and query users
from .models import User


#* ----------------------------------------------------------------------------
#* RegisterSerializer
#* ----------------------------------------------------------------------------
# Handles user registration - validates input and creates a new user in the database.
#
#  Fields behavior :
#    - username   : standard field, automatically handled by ModelSerializer
#    - email      : standard field, format validated by DRF automatically
#                   + custom validate_email() checks uniqueness in database
#    - password   : redefined manually as CharField because it needs special
#                   handling (write_only + password strength validators)
#    - avatar_url : does not exist in DB (@property in model), redefined as
#                   SerializerMethodField to calculate it manually via get_avatar_url()
class RegisterSerializer(serializers.ModelSerializer):

    #& STEP 1 : specifications

    # Redefined manually because it needs special specifications :
    # write_only=True          → received from Angular but NEVER returned in response
    # required=True            → field is mandatory
    # validators=[validate_password] → calls Django's built-in password rules :
    #   - MinimumLengthValidator  : minimum 8 characters
    #   - CommonPasswordValidator : rejects common passwords ('123456', 'password'...)
    #   - NumericPasswordValidator: rejects passwords with only numbers
    password = serializers.CharField(
        write_only=True,
        required=True,
        validators=[validate_password]
    )

    # Redefined manually because avatar_url does not exist in the database.
    # It is a @property in the User model calculated dynamically.
    # SerializerMethodField means : "I will handle this field manually"
    # DRF will automatically call get_avatar_url() to get the value.
    # Always read_only by default (cannot be sent by Angular)
    avatar_url = serializers.SerializerMethodField()

    #& STEP 2 : declare Meta (model and fields to serialize)

    class Meta:
        model = User
        # Tells the serializer which Django model to base itself on
        # ModelSerializer will automatically generate fields from this model

        fields = ('username', 'email', 'password', 'avatar_url')
        # Define fields to expose in this serializer
        # - 'username'   : required input from Angular
        # - 'email'      : required input from Angular
        # - 'password'   : required input, write_only (never returned in response)
        # - 'avatar-url' : read_only, generated by the @property in the User model

    #& STEP 3 : Custom handlers (field getters, validators and object creation)
URL router - maps each endpoint to its corresponding View.
    def get_avatar_url(self, obj):
        # Called automatically by DRF when building the response.
        # obj is the User instance just created.
        # Uses the @property defined in the User model :
        #   - If avatar uploaded → returns the real file URL
        #   - If no avatar       → returns DiceBear robot URL based on username
        return obj.avatar_url
    
    def validate_email(self, value):
        # Level 2 custom validation - called automatically by is_valid()
        # value = the email entered by the user
        # Checks that no other user already has this email in the database.
        # This rule is not automatic - DRF doesn't know it's required here.
        if User.objects.filter(email=value).exists():
            raise serializers.ValidationError("Email already exists.")
        return value
    
    def create(self, validated_data):
        # Called automatically by serializer.save() in the View.
        # validated_data = all fields already validated by is_valid()
        # create_user() is used instead of create() because it automatically
        # hashes the password - NEVER store a plain text password in the database.
        user = User.objects.create_user(
            username=validated_data['username'],
            email=validated_data['email'],
            password=validated_data['password'],
        )
        return user

#* ----------------------------------------------------------------------------
#* UserSerializer
#* ----------------------------------------------------------------------------
# Handles user profile display.
# Used after login to return user information to Angular.
# No validation needed - read only, no data creation.
#
# All fields except avatar_url are automatically handled by ModelSerializer
# because they exist directly in the database.
# avatar_url is redefined as SerializerMethodField because it is a @property.
class UserSerializer(serializers.ModelSerializer):
    
    #& STEP 1 : specifications
    
    # Redefined manually because avatar_url does not exist in the database.
    # SerializerMethodField means DRF will call get_avatar_url() automatically.
    avatar_url = serializers.SerializerMethodField()
    
    #& STEP 2 : define Meta (model ans fields to serialize)
    class Meta:
        model = User
         # All these fields exist in the DB - automatically handled by ModelSerializer
        # avatar_url is the only exception - calculated via get_avatar_url()
        fields = ('id', 'username', 'email', 'avatar_url', 'is_online', 'role')
    
    #& STEP 3 : Custom handlers (field getters, validators and object creation)
    def get_avatar_url(self, obj):
        # Uses @property defined in the user model
        return obj.avatar_url
    
#* ----------------------------------------------------------------------------
#* LogoutSerializer
#* ----------------------------------------------------------------------------
