# Generated by Django 6.0.5 on 2026-05-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'Friend Request', 'verbose_name_plural': 'Friend Requests'},
        ),
    ]
