# Generated by Django 6.0.5 on 2026-05-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friendship'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_friendship_pair',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
