# Generated by Django 6.0.5 on 2026-05-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_remove_friendship_unique_friendship_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
