# Generated by Django 6.0.5 on 2026-05-25 01:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_remove_friendship_unique_friendship_pair_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('from_user', 'to_user'), name='unique_accepted_friend_request'),
        ),
    ]
