# Generated by Django 6.0.6 on 2026-06-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_add_is_2fa_enabled'),
        ('friends', '0010_alter_friendrequest_accepted_at_and_more'),
    ]

    operations = [
    ]
